### ISSUE TITLE
v1.0.0-alpha Built-in Pop-up missing Close button

### ISSUE THREAD

**Issue by BrettEBowman** [fratsloos/fr24_card#27]
I just installed the new 1.0.0-alpha version. It is a nice improvement!

One bug/problem that I noticed is when I use the built-in pop-up window, I'm not seeing a "X" button to close it. Maybe it is something with my card_mod setup???

Here's my card config:

```yaml
type: custom:fr24-card
entity: sensor.msp_piaware_flights
providers:
  adsbexchange: false
  flightaware: true
  flightradar24: true
  opensky_network: true
  plane_finder: false
columns:
  - flag
  - registration
  - flight
  - icon
  - altitude
  - speed
  - distance
hide:
  empty:
    - distance
    - altitude
  ground_vehicles: true
popup: true
zone: zone.home
sort: distance
```
