### ISSUE TITLE
Config of popup should be an object

### ISSUE THREAD

**Issue by lloydbayley** [fratsloos/fr24_card#35]
This is a weird one...
The card will not display and shows and error complaining about the Config of popup should be an object.

<img width="380" alt="Screenshot 2024-01-15 at 1 57 14 am" src="https://github.com/fratsloos/fr24_card/assets/21309308/241b56db-b4dc-49ab-b3ca-541d8a767bc8">

No matter what I set popup to, either true or false, the error remains.
Now, if I remove the entire popup: true line, then the card displays properly.

The only thing I did recently was to add the card-mod entry to my configuration.yaml as I wanted more features as a front-end module rather than just as a lovelace resource.

```
# Front End/Theme Definitions
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/plugins/card-mod.js
    - /local/community/lovelace-card-mod/card-mod.js. <-------------------- ADDED THIS LINE
```

However, upon removing the line and putting it back to how it was, the problem is not solved so perhaps I'm barking up the wrong tree and it's just a coincidence and nothing to do with that change?!?!?!?!?!

Any thoughts?
