### ISSUE TITLE
Falling at the first hurdle - probably me!

### ISSUE THREAD

**Issue by mamvcivm** [fratsloos/fr24_card#40]
Hi, I've copied the contents of the _fr24_card-master_ folder into here: \\homeassistant\config\www\fr24card

but I'm confused by the second step:

**Preparation**

_To use the card you need to create a sensor that reads the JSON from Dump1090. Add the following configuration to your sensors.yaml:..._

- platform: rest
  name: FR24 Aircraft
  resource: http://192.168.1.122/dump1090/data/aircraft.json
  value_template: "{{ value_json.messages }}"
  method: GET
  scan_interval: 15
  json_attributes:
    - now
    - aircraft

I can't find an existing **sensors.yaml** anywhere in my HA installation and if I'm meant to create one, where should I put it...?

Thanks,

Andrew

**Comment by fratsloos** [comment]
@mamvcivm Maybe this tutorial helps with understanding the yaml files in Home Assistant: https://opensource.com/article/21/2/home-assistant-custom-sensors.

**Comment by mamvcivm** [comment]
Thanks Elwin, I've fixed it now! 
I thought it'd be OK to add the sensor detail to the bottom of the configuration.yaml file, but this didn't work, so I created a separate sensors.yaml file and referenced it in the configuration.yaml. 

I'm now wondering if I can create three separate cards, one for each of my FR24 feeders...?

**Comment by fratsloos** [comment]
That should be possible, as long as you add them as different sensors in your Home Assistant. You can do that with changing the `name`.

Example:

```yaml
- platform: rest
  name: FR24 Aircraft Feed X
  resource: http://dump1090-host/dump1090/data/aircraft.json
  value_template: "{{ value_json.messages }}"
  method: GET
  scan_interval: 15
  json_attributes:
    - now
    - aircraft
- platform: rest
  name: FR24 Aircraft Feed Y
  resource: http://other-dump1090-host/dump1090/data/aircraft.json
  value_template: "{{ value_json.messages }}"
  method: GET
  scan_interval: 15
  json_attributes:
    - now
    - aircraft
```

And then using that where you add the card:

```yaml
cards:
  - type: custom:fr24-card
    entity: sensor.fr24_aircraft_feed_x
  - type: custom:fr24-card
    entity: sensor.fr24_aircraft_feed_y
```

I have tested with multiple cards on the same page, it can cause issues with the speed of loading the dashboard.
